<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pb_social"
 *
 * Auto generated by Extension Builder 2014-11-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Social Media Streams',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Mikolaj Jedrzejewski, plus B',
	'author_email' => 'info@plusb.de',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.4',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.0-7.99',
			'php' => '5.3-5.6.99',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);